### ISSUE TITLE
messages

### ISSUE THREAD

**Issue by marcosstar** [redraskal/GhostScavengerHunt#1]
Hi, I'm setting up the plugin for a small Christmas event.

There are things that I do not understand and they are:

-Because when you find a head, it tells you that you already found that head?
It is not enough with: You found a ghost! (x / x)?
[Photo](https://fotos.subefotos.com/022686b794b01019c16c222047dfdf9do.png)
-Another thing, that I really do not know, if it's my problem?

When you find a head that you already found, the message multiplies:
You already found this ghost! 
You already found this ghost! 
[Photo](https://fotos.subefotos.com/b24986f54bd1940570f412548b6f684ao.png)

Thank you in advance for the development of the plugin

**Comment by redraskal** [comment]
There is an "already found" message so players can have a reminder that they clicked that skull at one point, and it's not the server thinking incorrectly.

As for the message multiplication issue, what version of spigot are you using?

**Comment by marcosstar** [comment]
the latest version 1.12.2

Regarding the message "You already found this ghost!" When you find a new ghost, I do not see any sense, it's clear that this ghost has already found it, I think it's a spam in the unnecessary chat.


You found found a ghost! (x/x)
Find all of them to earn a super reward!
¿¿ You already found this ghost ! ??

**Comment by redraskal** [comment]
What if you were to login a week later and forgot if you clicked on x ghost or not? If you tried clicking it and received no response, you could assume that either you already found it or the plugin is not functioning properly, since it should display some response to these special skulls, right?

The message kind of differentiates these special custom skulls from normal skulls you just place on the ground. As for the message duplication, I don't know why 1.12.2 duplicates the message. 1.8.8 doesn't duplicate it, and the API is still the same for sending messages to players.

If I can't find a reason as to why this message is duplicating itself for no apparent reason, I'll just remove it.

**Comment by marcosstar** [comment]
It seems that I have not explained myself well, I will try to do better.

the message "You already found this ghost!" It should not be deleted, as you say, the user should know that he has already found that head, even if that message is duplicated, that is indifferent.

The message that I see totally unacceptable is:

When a user, for the first time, finds a ghost, the message "You already found this ghost!"
Evidently you already found that ghost, in fact right now.

This is what I mean, I just clicked the first ghost, nothing more:

[photo click here](https://fotos.subefotos.com/022686b794b01019c16c222047dfdf9do.png)
